export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LIBRARY_ROUTE = '/library'
export const BASKET_ROUTE = '/basket'
export const LIBPAGE_ROUTE = '/libpage'